/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Float, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["React-Logo_Material002_0"]: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
};

const ReactLogo = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/models/react.glb") as GLTFResult;
  return (
    <Float floatIntensity={1}>
      <group position={[8, 8, 0]} scale={0.4} {...props} dispose={null}>
        <mesh
          geometry={nodes["React-Logo_Material002_0"].geometry}
          material={materials["Material.002"]}
          position={[0, 0.08, 0.18]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.39, 0.39, 0.52]}
        />
      </group>
    </Float>
  );
};

useGLTF.preload("/models/react.glb");
export default ReactLogo;
